### ISSUE TITLE
[Sprint5] TODOs

### ISSUE THREAD

**Issue by koyrkr** [swsnu/swpp2020-team8#110]
### Date
2020/11/28

우리의 약속
- 다 한 것은 꼭! 체크하기~~~
- 아래의 분담 사항은 꼭 지키되, 부담이 될 만한 것은 먼저 시도해보고 안되면 도움 요청하기~~
- 서로서로 많이 도와주고, 

## Time Schedule

11/30 (월) Sprint4 마무리 (아래의 TODO 참고)
12/1 (화) Sprint5 #1 meeting
12/3 (목) Sprint5 #2 meeting
12/8 (화) Sprint5 #3  meeting
12/10 (목) User Testing (@SWPP 실습)
12/15 (화) Sprint5 #4 meeting
12/17 (목) Final Poster Session
12/18 (금) Final Report Submission

## TODOs in Sprint5

@GooJinSun 
수정사항을 프론트에 반영하기
- [ ] Noti example response(모델별로)
- [ ] ResponseRequest
- [ ] 자동로그인 jwt refresh
- [ ] 백 로그인 session auth --> jwt token
- [ ] Detail page permission 처리 

(이후)
- [ ] 모바일 대응 분배하기

@koyrkr
된 것들 다시 한 번 확인하기
- [ ] Comment 비밀댓글/삭제 시 alert
- [ ] 전체 피드 리스트에서 전체/친구/익명 공개 범위에 따라 작성자 정보
- [ ] Login 후 헤더
- [ ] 백엔드 위키 업데이트

(이후)
- [ ] 영상 콘티 기획
- [ ] 영상 촬영 스케줄

@curious-curie
- [ ] FriendList api, 프론트 연결확인(FriendItem)
- [ ] FriendRequest api, 프론트 연결확인(FriendItem)

(이후)
- [ ] 디플로이 백/프론트 (어려울시 도움 요청!)
- [ ] 포스터 만들기
- [ ] 캐싱

@ssm0318
- [ ] ML수정
- [ ] Permission 추가, 테스팅
- [ ] 백 전체적으로 손보기(Noti), 테스팅

(이후)
- [ ] Locust
- [ ] 영상콘티
- [ ] 발표준비

그 외
- [ ] 피드 렌더링하는 속도가 느린 이유 찾기
- [ ] 피드 분기문 찾기
- [ ] 프론트엔드 테스팅 꾸준히
- [ ] mock data 일관성있게 바꾸기
- [ ] 디플로이 영상 얼른하기 12월 1일까지
- [ ] Final Report

**Comment by ssm0318** [comment]
잘 부탁드리오 스장님아~~~~~~~~~~

**Comment by GooJinSun** [comment]
지나 스장님 잘부탁드립니다아
