### ISSUE TITLE
[Sprint 4] To-do 

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#46]
### DUE: 11/24 (Tues) 6PM

[Frontend]
* 규리
- [x] <NewComment/ >, <CommentItem/ >
- [x] Friends Page
- [ ] Post Edit/Delete API Linking

* 지나
- [ ] <PostDetail/ > + API linking
- [ ] <QuestionSendModal/ >

* 재원
- [ ] UserPage
- [ ] Search + Search Results Page

* 진선
- [ ] <FriendWidget/ >  API linking
- [ ] Question Detail Page
- [ ] Notification Page + Noti API linking

[Backend]
* 규리
- [x] Notification model + serializer (including JSON validation) + Notification view for Like, Comment
- [ ] API testing for implemented views

* 지나
- [ ] [FriendShip], [Friend Request] Model + Serializer (including JSON validation) + View
- [ ] Notification view for [Friend Request] + [Friendship]
- [ ] API testing for implemented views

* 진선
- [ ] [Response Request] Model + Serializer (including JSON validation) + View
- [ ] Notification view for [Response Request] (including response)
- [ ] API testing for implemented views

* 재원
- [ ] user search view + API testing
- [ ] JSON validation for Comment, Like, Article, Response, Question, Post, Profile, Auth
- [ ] API testing for Comment, Like, Article, Response, Question, Post, Profile, Auth
- [ ] ML feature

**Comment by ssm0318** [comment]
- 프사, 아이콘
- 모바일 대응

**Comment by GooJinSun** [comment]
- coveralls 업데이트 확인해보기

**Comment by ssm0318** [comment]
1. 헤더 밑에 margin을 늘리는 것은 어떨지?

2. 로그인 화면에서 회원가입 버튼은 색상을 변경하거나 hyperlink로 변경하고 엔터만 쳐도 로그인이 되게 하는 것은 어떨지?

3. Timeago로 timestamp 자동 업데이트

**Comment by curious-curie** [comment]
* friendRequest 관련 액션 수행 위치 - noti or friend reducer ?
* popup component 도입,,,

**Comment by ssm0318** [comment]
locust
caching

**Comment by curious-curie** [comment]
* Like API LINKING
