### ISSUE TITLE
[Sprint 4] Curious Curie's Daily To-do Coverage Report

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#47]
[Frontend]
- [X] clean Sprint3 ddong
- [x]  <NewComment/ >, <CommentItem/ >
- [x] Friends Page
- [ ] Post Edit/Delete API Linking

 

[Backend]

- [x]  Notification model + serializer (including JSON validation) + Notification view for Like, Comment
- [x] API testing for implemented views

<br> 

To-do | To-do-detail | progress | Etc
-- | -- | -- | --
sprint 3 덩치우기 | sign up API linking | 100% |  
  | redirect bug fix | 100% |  
  | user module test | 100% |  
  | create post linking | 100% |  
  | select questions API linking | 70% | GET sample questions
Comment  component | CommentItem | 90% |  
  | NewComment | 90%  |  
Post APIs | PostEdit API linking |   |  
  | PostDelete API linking |   |  
Friends Page | FriendsPage |  100% |  
Friends Page | Related Components |  100% |  
Noti | Model | 100% | 최대한 빨리 진행하기
  | Serializer |  100% | 최대한 빨리 진행하기
` | JSON validation |   |  
Noti View | for Like, Comment | 100%  |  
  | api testing |  100% |  
시간 남으면 | feed 모바일 대응 해봐야징 |   |

**Comment by curious-curie** [comment]
**오늘 한 일** 
- [X] clean Sprint3 ddong

(GET sample question은 주석처리 해놓고, db 연결 해놓고 나서 실제 데이터로 바꿔야겠다. 그래야 seed data 혹시 잘못 설정해서 결과가 왜곡되는 일이 없을 테니)

**내일 할 일**
- [ ] Comment 관련 작업 끝내기
- [ ] Noti 모델 시작

**오늘 힘들었던 일** 
오늘 처음으로 FE testing mock할 때 에러 mock을 해보았습니다.
promise를 resolve 하지 않고 reject 하는 방식입니다. 
```
    axios.post.mockReturnValue(Promise.reject({ error: 'error' }));
    axios.get.mockReturnValue(Promise.reject({ error: 'error' }));
```
이런식으로 엄청 간단한데, 우리 항상 action할 때 에러 처리 하니까
빼먹지말고 @@_@@@_FAILURE 시의 경우도 꼭 테스팅 하기!!

그리고 json response object 테스팅 할 땐 toEqual 아니라 toMatchObject를 써야 stringify?된 것과 비교를 제대로 하더라는 것도 깨달았습ㄴ다.

**Comment by curious-curie** [comment]
오늘 개발은 signup redirect 코드 수정 빼고는 하지 못하였습니다...
그러나 유익한 백엔드 세미나를 들어서 한층 성장한 기분입니다.
목요일 오전까지 중요한 일이 있어서 그것만 끝내고 
와다다 개발 폭격하도록 하겠습니다...!
내일은 CommentItem Reply 반영하여 마크업 + NewComment 마크업 정도는 끝내려고 합니다.
aza aza

**Comment by curious-curie** [comment]
11/18 
오늘 한 일
- Friend Page 관련 개발 시작
- Friend Status Buttons, FriendItem 
- CreatedTime 업데이트
- App.jsx redirect 해결

11/19 할 일
- Friend Page 관련 작업 마무리
- Friend 관련한 것들 모두 테스팅 

어려웠던 일 
- redirect 문제 해결했다
login, signup 각각 패쓰를 다르게 줬음에도 불구하고 코드에서 from path url과 상관 없이 코드의 윗 줄에 있는 패쓰로 리다이렉트 되는 문제였는데 syntax 문제였다.
슬랙에도 공유했지만 from을 써서 해결해야 한다!~ 
[Img](https://files.slack.com/files-pri/T01AAQM97FX-F01EL9FCD55/image.png)
이미지가 왜 안보일까?

**Comment by curious-curie** [comment]
오늘 한 일 
- Friend Page 관련 작업 끝
- 테스트까지 완료
- Comment Item 관련 작업 시작 
- Login, Sign Up Page 및 화면 흔들림 수정 
- Dialog Component 구현

내일 할 일
- Comment 관련 작업 마무리
- Noti 모델링 시작 

하고싶은 말
- Dialog Component 맣ㄴ이 사랑해주세요~

**Comment by curious-curie** [comment]
11/20 (금)

오늘은 비공식적인 규리의 쉬는날 이었습니다.
Comment Item 관련한 고민만 조금 해보았습니다.
Reply일 때, 아닐 때 padding같은 UI 적인 것들도 다르고
안에 들어가는 data도 다르다 보니 state나 UI에서 조건에 따라 달라지는 것이 많을 것 같아
+ CommentItem 안에 Reply 들을 다시 CommentItem으로 불러오는 재귀적인 관계를 만들어야 해서
CommentItem이랑 ReplyItem 으로 나눌지, 아니면 하나의 컴포넌트로 할 지 고민중에있습니다.
Comment쪽이 생각보다 컴포넌트가 복잡해서,, 꽤나 어려울 것 같네요

11/21 계획
* Notification 모델링 및 테스트 
* Comment 관련 작업 마무리

**Comment by curious-curie** [comment]
11/21 (토)

### DONE
* Noti Modeling
* Noti Model Testing
* Noti Serializer 
* comment related components, action
* comment related components testing 

### IN PROGRESS
* comment related reducer: 리스트 / 디테일 페이지 명시 명확하지 않아 논의 후에 하려구 함 

### 어려웠더 것 
notification modeling에서 target, origin `GenericForeignKey` relation
두 가지 GenericForeignKey field가 있기 때문에 
default param인 content_type, object_id 쓰지 않고 target_type, target_id / origin_type, origin_id 사용했다.
그러다 보니 ForeignKey로 참조하고 있던 모델에서 GenericRelation을 통해 노티와의 관계를 명시할 때 문제가 있었다.
Notification 모델에서 content_type을 찾을 수 없다는 그런 에러가 났다. 왜냐면 content_type 필드가 노티에 없기 때문에 

그래서 원래 기존에 다른 모델들에서 그냥 `GenericRelation(Article)` 이렇게 하면 안됐고
` GenericRelation(Notification,
        content_type_field='target_type', object_id_field='target_id')`
이런 식으로 필드를 명시해줘야 했다!

**Comment by curious-curie** [comment]
한 일 추가 
post_save 시그널 활용,  Like, Comment생길 때마다  Noti 생성 
views.py 에다가 해야할지 고민했는데,
```
However, if you always "want Bar created every time Foo is created", then I would do this by catching the Foo Model's post_save signal and create the required Bar. That makes sure that Bar is created, even if you create a Foo in the shell, for example.
```
(https://stackoverflow.com/questions/36219759/how-to-add-two-different-models-in-perform-create-in-rest-framework)

보고 post_save를 활용해서 구현하였는데
혹시 이것이 비효율적인 방법일까요 ...? 내일 얘기해보아요 

구현 내용
```
@receiver(post_save, sender=Like)
def create_noti(sender, **kwargs):
    instance = kwargs['instance']
    target = instance
    origin = instance.target
    actor = instance.user
    recipient = instance.target.author
    message = f'{actor.username} likes your {origin.type}'
    Notification.objects.create(actor = actor, recipient = recipient, message = message,
            origin = origin, target = target, is_read = False, is_visible = True)
```
이런식

**Comment by curious-curie** [comment]
11/22 오늘도 Noti 이어서 완료
API TestCase 및 View 정비했고
알람은 author나 friend가 아니라 recipient에 따라 노출 여부가 바뀌어야 하기 때문에 그 부분을 신경써서 함
`isRecipient` custom permission class를 만들어서, recipient만 읽음처리 할 수 있도록 처리~ 함

**Comment by ssm0318** [comment]
noti 모델에 default value들을 적절히 활용해서 너무 많은 parameter을 주지 않아도 되게 하는 것도 좋을 것 같아요~
이를테면 noti를 처음 만들 때 , is_read = False, is_visible = True 이런거 굳이 안 줘도 되니까?

**Comment by curious-curie** [comment]
11/23,24 noti PR feedback 반영하여 고치기 및 frontend comment related + delete post  작업

unique constraint로 중복된 (타겟, 오리진 id 등등과 메시지까지 중복된!!) 노티를 못 만들도록 해놨는데, seed 심을 땐 랜덤 데이터가 들어가기 때문에 중복된 노티가 생성될 여지가 있었음
그래서 
```
    try:
            Notification.objects.create(actor = actor, recipient = recipient, message = message,
                origin = origin, target = target)
    except IntegrityError as error:
        if 'unique constraint' in error.args:
            pass
```

에러 나도 무시하고 (create하지 않고) 다음 코드로 진행되도록 try except를 썼었는데, 테스트에서 폭풍 오류가 발생함…

django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

이런 에러였고, 검색해보니 

 However, in Django 1.5/1.6, each test is wrapped in a transaction, so if an exception occurs, it breaks the transaction until you explicitly roll it back. Therefore, any further ORM operations in that transaction will fail with that django.db.transaction.TransactionManagementError exception.

이렇다고 함~! 귀찮아서 해석은 안하겠음
자세하겐 모르겠는데, 테스트 뿐 아니라 실제 상황에서도 발생할 Integrity Error 및 그에 따라 발생하는 저런 에러를 대비하기 위해서는 코드단에서 방어가 필요하다고 생각,,, 

그래서 해결책은 
```
    try:
        with transaction.atomic():
            Notification.objects.create(actor = actor, recipient = recipient, message = message,
                origin = origin, target = target)
    except IntegrityError as error:
        if 'unique constraint' in error.args:
            pass

```


이렇게 transaction.atomic으로 감싸는 것! 이라고 한다 … 너무 어렵네

**Comment by ssm0318** [comment]
근데 마지막에서 위랑 아래 코드 차이가 머야?

**Comment by curious-curie** [comment]
transaction.atomic 더한거! 그거를 써서 transaction 의 원자성을 보장 => 저거 쓰기 전에는 테스트 케이스 (하나의 트랜잭션으로 취급하는 듯) 단위에서 에러가 나서 그 이후에 모든 것들이 실행이 안됐는데, transaction.atomic()을 써줌으로써 하나의 트랜잭션을 덩어리로 판단하고 익셉션을 캐치하는 ..? 그래서 트랜잭션 한 단위의 실행을 보장해주는 느낌이라고 이해했어 근데 전혀 틀릴 수 있어 @ssm0318

**Comment by ssm0318** [comment]
오오오오오오오오 짱신기하다 좋은 정보 공유 감사함당~~~

**Comment by curious-curie** [comment]
## 무한스크롤 구현 using Intersection Observer
타겟 엘레멘트와 타겟의 부모 혹은 상위 엘레멘트의 뷰포트가 교차되는 부분을 비동기적으로 관찰하는 API ⇒ 결국 타겟 element가 화면에 노출되었는지 여부 구독하는 방법

### - methods

`IntersectionObserver.observe(target)`: 관찰 시작

`IntersectionObserver.unobserve(target)`: 관찰 종료

`IntersectionObserver.disconnect(target)`: 관찰 멈추기

1. `Intersection Observer` 객체를 생성하면서, `Callback Function` 과 `option` 을 전달한다.
2. `Intersection Observer` 에서 observe 로 구독할 `Target Element` 를 추가한다.
3. `Target Element` 가 options.threshold 로 정의한 **Percent**(%) 만큼 화면에 노출 혹은 제외 되면, entries 배열 에 추가하고, `Callback Function` 을 호출한다.
4. `Callback Function` 에서 전달 받은 entries 배열을 확인하면서, **isIntersecting** 으로 노출 여부를 확인한다.
5. 만약 더이상 `Target Element` 를 구독할 필요가 없다면, IntersectionObserver 에서 **unobserve** 로 제거 할 수 있다.

## 왜 쓸까?

window.addEventListener을 이용한 스크롤 이벤트 구현할 때의 비효율성을 어느 정도 해결해준다. 

### 1. 호출 수 제한 방법 debounce, throttle을 사용하지 않아도 된다.

`debounce`와 `throttle`은 스크롤 이벤트로 인해 발생하는 불필요한 함수 호출 수를 컨트롤할 필요가 있음.

console.log가 수도없이 호출됨 

```
window.addEventListener('scroll', function() {
   return console.log('scroll!');
});
```

### 2. reflow를 하지 않는다.

스크롤 이벤트에서는 현재의 높이 값을 알기 위해`offsetTop` 을 사용하는데 정확한 값을 가져오기 위해 매번 layout을 새로 그리게 된다.

⇒ 렌더 트리를 재생성 하는 것이기 때문에 브라우저 성능 저하
