### ISSUE TITLE
[Sprint 4] FireFighting GooJinSun's Daily To-do Coverage Report

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#48]
[전체 to-do](https://github.com/swsnu/swpp2020-team8/issues/46)

### 소방수 진선의 sprint4 To-do

[Frontend]
- [ ] <FriendWidget/ > API linking
- [x] Question Detail Page
- [ ] Notification Page + Noti API linking

[Backend]
- [x] [Response Request] Model + Serializer (including JSON validation) + View
- [x] Notification view for [Response Request] (including response)
- [x] API testing for implemented views

[E2E Testing]
- [ ] Response
- [ ] Post
- [ ] Like (like count, user liked, duplicate)
- [ ] Auth
- [ ] Response Request

[Plans]
| To-do | To-do-detail | progress | dependency |
|-|-|-|-|
| sprint 3 마무리  | question feed api linking | 100% | 화요일 전까지 완료하기 |
| | `<QuestionItem>` test coverage 100% 달성| 100% | |
| | `<QuestionListWidget>` test coverage 100% 달성| 100% | |
| | question redux module test coverage 100% 달성| 100% | |
| Question Detail Page | markup | 100% | 아무때나 |
| | api linking | 100% | |
| | frontend testing | 100% | |
| Response Request | model | 100% | 최대한 빨리 진행하기 |
| | serializer | 100% | 최대한 빨리 진행하기 |
| | view | 100% | 최대한 빨리 진행하기 |
| | api testing | 100% | 최대한 빨리 진행하기 |
| `<FriendWidget/>` | api linking | 95% | Friend model/view 완료되면 시작 |
| | frontend testing | 95% | |
| Noti ResponseRequest | view | | |
| | api testing | | |
| Notification Page | markup| 100% | 아무때나 |
| | api linking | 50% | Notification 모델 완료되면 시작 |
| | frontend testing | 50% | Notification 모델 완료되면 시작 |

**Comment by GooJinSun** [comment]
[2020-11-15-SUN]

작업중인 브랜치: `feature/frontend-questions`

**오늘의 계획**
- sprint 3에 못 다한 일 마무리하기
  - [x] #43 @ssm0318 가 고쳐준 api 연결하기
  - [ ] Question Feed 관련 테스팅하기

#### 어려웠던 점
- 

#### 내일의 계획
- [ ]

**Comment by ssm0318** [comment]
오~~~~~~~~~~~ 정리 방식 개쩌는데~~~~~~ 천재왕 천진순이세요?

**Comment by ssm0318** [comment]
우와 technical difficulty 정리도 너무 좋다 저런걸 따로 모을 수 있는 방법이 없으려나? 보통 어떻게 하지? @GooJinSun 
소방수 멋져...☆

**Comment by ssm0318** [comment]
포맷 좀 베껴가겠습니다~~~ 감사합니다~~

**Comment by GooJinSun** [comment]
@ssm0318 difficulty정리는... 음 한번도 3명 이상의 팀에서 해보지 않아서 잘 모르겠는데
@curious-curie @koyrkr 혹시 해본 방식이나 좋은 아이디어 있는 사람??
팀에서 공유되면 좋을만한 bug solution?해결방법? 시도 한것들 공유하고 정리하는 법??

**Comment by curious-curie** [comment]
개쩔어 ㅠㅠ 저도 포맷좀 훔쳐갔ㅇ어용~
어려웠던 점은 흠 다 difficulties 모으려면 wiki에 따로 적거나 하는게 낫지 않을까????

**Comment by koyrkr** [comment]
@GooJinSun 저도 포맷 좀 이용하겠슴다~~ (이미 이용했음) 이용해보니까 조금 더 하루하루의 어려웠던 점, 새로 알게된 점을 정리할 수 있어서 좋은 것 같아용!

으응 technical difficulty를 다 모으려면... wiki도 좋구 저번에 보니까 노션이 좀 더 (wiki보다는) 에딧하기가 편해보이던데.. 오늘 회의때 한번 어떻게 정리해볼지 간단하게 얘기 나눠봐요!

**Comment by GooJinSun** [comment]
[2020-11-15-SUN]

작업중인 브랜치: `feature/frontend-questions`

**오늘의 계획**
- sprint 3에 못 다한 일 마무리하기
  - [x] `<QuestionItem/>`, `<QuestionListWidget/>` test refactoring
  - [ ] question redux module test coverage 100% 달성
  - [ ] Response Request model

#### 어려웠던 점
- 컨디션 난조로 목표했던 개발 사항 마무리 못함ㅠ

#### 내일의 계획
- [ ] question redux module test coverage 100% 달성
- [ ] Response Request model

**Comment by GooJinSun** [comment]
[2020-11-16-MON]

작업중인 브랜치: `feature/frontend-questions`

**오늘의 계획**
- sprint 3에 못 다한 일 마무리하기
  - [x] question redux module test coverage 100% 달성
  - [ ] Response Request model

#### 어려웠던 점
- `axios.reject` test

#### 내일의 계획

**Comment by GooJinSun** [comment]
[2020-11-16-MON]

작업중인 브랜치: `feature/frontend-questions`

**오늘의 계획**
- [ ] sprint 3 pr날리기 
- [ ] Response Request model
- [ ] Response Request serializer
- [ ] Response Request model test

#### 어려웠던 점
- Error: Error: connect ECONNREFUSED 127.0.0.1:3000 in `SignUp.test`
```javascript
 PASS  src/pages/SignUp.test.jsx
  ● Console

    console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: connect ECONNREFUSED 127.0.0.1:3000
          at Object.dispatchError (/Users/jinsun/swpp2020-team8/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at EventEmitter.<anonymous> (/Users/jinsun/swpp2020-team8/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at EventEmitter.emit (events.js:326:22)
          at Request.<anonymous> (/Users/jinsun/swpp2020-team8/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:412:47)
          at Request.emit (events.js:314:20)
          at Request.onRequestError (/Users/jinsun/swpp2020-team8/frontend/node_modules/request/request.js:877:8)
          at ClientRequest.emit (events.js:314:20)
          at Socket.socketErrorListener (_http_client.js:469:9)
          at Socket.emit (events.js:314:20)
          at emitErrorNT (internal/streams/destroy.js:100:8) undefined
```
[[stackoverflow] Cross-Origin HTTP Request originating from server-side NodeJS/Axios/JSDOM
](https://stackoverflow.com/questions/51054286/cross-origin-http-request-originating-from-server-side-nodejs-axios-jsdom)로 해결해보려 했으나, 한줄 추가하고 테스트에서 promise.reject 관련 수많은 오류가 발생함
```javascript
(node:87240) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
```
 디버깅해보니,,, `Signup.test`에 axios를 잘못 임포트해오고 있었음(csrf 토큰, 쿠키 세팅해둔 axios인스턴스가 아닌 그냥 axios(`import axios from 'axios'`)을 발견함
#### 내일의 계획

**Comment by GooJinSun** [comment]
오늘 할일
- [ ] serializer
- [ ] csrf token testing

**Comment by GooJinSun** [comment]
[2020-11-21-SAT]

작업중인 브랜치: `feature/frontend-question-detail`, `feature/frontend-question-detail`, `feature/fronntend-notification-page`

**오늘의 계획**
  - [x] Question Detail Page
    - anonymous post item 처리
    - 익명의 글 보기 기능 추가해야 함
  - [x] Notification Page markup

#### 어려웠던 점
- QuestionDetail Page의 익명의 글 보기에서 답변리스트를 필터링할 때 생기는 문제 ~아직 해결못함~
![image](https://user-images.githubusercontent.com/37523788/99876698-b79acc00-2c3b-11eb-97c9-10a0a1d68701.png)


#### 내일의 계획
- [ ] ResponseRequest serializer / view
- [ ] ResponseRequest api testing
- [ ] csrf token testing

**Comment by GooJinSun** [comment]
[2020-11-21-SAT]

작업중인 브랜치: `feature/frontend-question-detail`

**오늘의 계획**
- [ ] Csrf token testing
- [ ] Response Request
  - View
  - JSON Validation / API testing
  - Unique together


#### 어려웠던 점

#### 내일의 계획

**Comment by GooJinSun** [comment]
[2020-11-22-SUN] [2020-11-23-MON]
작업중인 브랜치:

**오늘의 계획**
- [x] ResponseRequest View, API testing
- [ ] Post Edit page (api, testing, page markup)
- [ ] Question detail (View anonymous)
- [ ] Noti Response Request
- [ ] Question Send Call

**어려웠던 점**
- API testing: 
ResponseRequest의 responded field를 업데이트하는 api `/api/feed/questions/:qid/request-response/:rid` 테스팅에서
![image](https://user-images.githubusercontent.com/37523788/99978371-34b77400-2de9-11eb-859b-7179c1c99e83.png)
에서  body에 데이터를 넣으려고 이렇게 하면,,,
```python
response = self.patch(self.reverse('response-request-detail', {'responded': True}, qid=question.id, rid=friend_user.id))
```
`400 Bad Request`가 발생한다..... 원인은 알 수 없지만 boolean value 의 타입과 관련해서 문제가 있는 것 같았따...
그래서 다음과 같이 json encoding을 해주었더니 해결이 되었따.......
```python
url = f'/api/feed/questions/{qid}/request-response/{rid}/'
        response = self.client.patch(url, json.dumps({'responded': True}), content_type='application/json')
        self.assertEqual(response.status_code, 200)
```

- API  testing:
```python
```

**내일의 계획**
