### ISSUE TITLE
[Sprint 4] YesWoman koyrkr's Daily To-do Coverage Report 

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#49]
[전체 to-do](https://github.com/swsnu/swpp2020-team8/issues/46)

_Last Updated:_ 2020/11/21

[Frontend]
- [x] Post Detail Page Markup
- [x] Post Detail Page API linking
- [x] Post Detail Page Testing
- [x] `<QuestionSendModal/>` Markup
- [x] `<QuestionSendModal/>` Testing
- [ ] `<QuestionSendModal/>` API Linking + testing `TBU`

[Backend]
- [x] [FriendShip] Model
- [x] [FriendShip] Serializer (including JSON validation)
- [x] [FriendShip] View `In progress` 
- [x] [Friend Request] Model
- [x] [Friend Request] Serializer (including JSON validation)
- [ ] [Friend Request] View `In progress`
- [ ] Notification view for [Friend Request]
- [ ] Notification view for [Friendship]
- [ ] API testing for implemented views `In progress`

| 어제 상태 | 어제 계획 | 현재 상태  | 내일 계획 |
|-|-|-|-|
| 0% | N/A | 0%  | `Post Detail Page` Markup ~ Testing|
| 0% |  `Post Detail Page` Markup ~ Testing | 13% | `Post Detail Page` API Linking + Friend Request Model|
| 13% |  `Post Detail Page` API Linking<br> Friend Request Model | 20% | [Friendship] Model<br> `Post Detail Page` new testing|
| 20% |  [Friendship] Model<br> `Post Detail Page` new testing | 23% | [Friendship] Model<br>`QuestionSendModal/` Markup|
| 23% |  Friendship] Model<br>`QuestionSendModal/` Markup | 30% | misc fixes + [Friendship] Model + seed.py|
| 30% |  misc fixes + [Friendship] Model + seed.py | 32% | misc fixed + [Friendship] Model + seed.py|
| 32% |  misc fixes + [Friendship] Model + seed.py | 70% | `<QuestionSendModal>` API linking + Model testing|

<작업 중인 브랜치>
- feature/frontend-postdetail (`Post Detail Page` 관련 작업 브랜치)
- feature/frontend-questionsend-modal (`<QuestionSendModal/>` 관련 작업 브랜치)
- feature/frontend-login-enter (`Login Page` enter key issue 관련 작업 브랜치)
- feature/frontend-anon-profile (`Anonymous Feed Page` profile issue 관련 작업 브랜치)
- feature/backend-friendrequest (Friendship + FriendRequest Model 관련 작업 브랜치) 

<어려웠던 점> 
- [`Post Detail Page` : post redux 관련](https://github.com/swsnu/swpp2020-team8/issues/49#issuecomment-728116628) 
- [`Post Detail Page` : useParams() ](https://github.com/swsnu/swpp2020-team8/issues/49#issuecomment-729039330)

**Comment by koyrkr** [comment]
[2020-11-16-MON]

작업중인 브랜치: `feature/frontend-postdetail`

#### 어려웠던 점
- `Post Detail Page` redux 관련
`post.js`에서 `getSelectedPost()` (현재는 그냥 mockData를 불러오는) 를 이용해서 제대로  selectedPost를 가져온다고 생각했는데 selectedPost를 제대로 가져오지 않으며 post의 관련 property (profile_pic 등)이 undefined 되었다는 에러가 떴다 ㅠㅠ 한참을 생각하고 console 창으로 디버깅을 해봤는데도 해결이 되지 않아 오랜 시간동안 애를 먹었다. 

  - solution
- 우선 @GooJinSun 이 알려준 [redux-devtools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) 를 이용해서 디버깅을 해보니 action, state, diff (전과 state가 어떻게 달라졌는지)를 한눈에 쉽게 볼 수 있었다! 앞으로도 자주 이용해야겠다! 다시 한번 감사쓰~~
- redux-devtools를 이용해서 확인한 결과 selectedPost를 제대로 가져오지 않는다는 사실을 확실히 알 수 있었다. 
- 원인은 바로바로 selectedPost의 initialState가 `{}`이라 속해있는 property를 제대로 참조하지 못하면서, `PostDetail.jsx` 에서 selectedPost의 유무도 판단해주지 않아서 생기는 문제였다. 물론 `post.js`에서 GET_SELECTED_POST_FAILURE와 관련된 action 정의를 해주면 되겠지만 `PostDetail.jsx`에서도 한번 걸러주는게 안전해보였다.
- 따라서
``` {selectedPost && <QuestionItem questionobj={selectedPost}>} 
와 비슷한 형식으로 코드를 바꿔주니 selectedPost를 아주 잘 가져오는 것 같았다!

#### 내일의 계획
- [ ] `Post Detail Page` API linking 제대로 작동하는지 확인
- [ ] Backend 구조 다시 한 번 살펴보면서 테스팅 과정 정확히 이해하기
- [ ] FriendRequest Model 건드려보기

**Comment by koyrkr** [comment]
[2020-11-17-TUE]

작업중인 브랜치: `feature/frontend-postdetail`

#### 어려웠던 점
- ##### (이제는 없어진) `Post Detail Page` API Linking : useParams
우선 useParams로 계속 맞게 id를 가져온다고 생각했는데 자꾸 안가져오는 것이었다. 

- ##### solution
useParams는 `/articles/:id`에서 `:id`와 같은 부분을 읽어오는 것이며, 그냥 `articles/1` 이렇게 상수로 주면 절대 못읽는다는 사실을 새롭게 알게 되었다. 


- ##### 느낀점
오늘 Backend Seminar를 들었는데 너무너무 걱정되지만 백엔드 마스터 @ssm0318 가 아주아주 열심히 고생해놓은 흔적을 따라가다보면 답을 찾을 수 있겠지..? 내일부터 꼭 Model 건드려봐야겠다! 그리고 Post Detail이 이제 3개 따로따로로 나눠졌는데 Post Detail을 열심히 해두니까 나머지 세개도 아주 어렵지 않게 진행할 수 있었다. 앞으로는 모든 것을 얼렁뚱땅 넘어가지 않고 열심히 해야겠다! 화이팅!

#### 내일의 계획
- [ ] `ArticleDetail`. `QuestionDetail`. `ResponseDetail` params로 type 넘겨주기? 혹은 이대로?
- [ ] `ArticleDetail`. `QuestionDetail`. `ResponseDetail` 테스팅 완료!
- [ ] FriendRequest Model 건드려보기 + 짜보기

**Comment by koyrkr** [comment]
[2020-11-18-WED]

작업중인 브랜치: `feature/frontend-postdetail`, `feature/backend-friendrequest`

#### 어려웠던 점
- ##### Backend Friendship Model
생각보다 BE와 친해지는데 시간이 오래 걸렸다.. 아직도 안친하지만.. 오늘 좀 익숙해진 것 같기도 하다...

- ##### solution
앞으로 더더더 이것저것 만져보는 것만이 해결책이겠지....


- ##### 느낀점
BE 화이팅....! 그래도 seed.py에 friendship 관련 seed도 넣었더니 기대대로 잘 동작하는 것 같기도 하고.. 내일은 testing을 통해서 뭐가 잘못되었는지 확인해봐야겠다!

#### 내일의 계획
- [ ] `Post Detail Page` Testing 100%
- [ ] `<QuestionSendModal/>` Markup
- [ ] Friendship Model 보완 및 테스팅 약간..?

**Comment by koyrkr** [comment]
[2020-11-19-THU]

작업중인 브랜치: `feature/frontend-postdetail`, `feature/frontend-questionsend-modal`, `feature/frontend-login-enter`, `feature/frontend-anon-profile`

#### 어려웠던 점
- 딱히 없었지만, 백엔드의


- ##### 느낀점


#### 오늘 한 일
- Post Detail Page 제대로 동작하도록 변경 (App.jsx 수정)
- 로그인 페이지 엔터키로도 작동하도록!
- `<QuestionSendModal/>` 마크업 수정 -> 아직 FriendItemList는 가져오지 않음
- 익명 피드 프로필 사진 안보이게 하기 위한 고민...? -> PostItem, QuestionItem에서 처리해야할 것 같다!

#### 내일의 계획
- [ ] friend 모듈 & FriendItem 풀 받고 `<QuestionSendModal/>` API Linking
- [ ] Friendship Model + seed.py 수정 최대한 많이 (토욜에 쫙쫙 할 수 있게)

**Comment by koyrkr** [comment]
[2020-11-20-FRI]

작업중인 브랜치: `feature/frontend-postdetail`, `feature/frontend-questionsend-modal`, `feature/frontend-login-enter`, `feature/frontend-anon-profile`

#### 어려웠던 점
- 딱히 없었다. 어제는 너무너무 피곤했었는지 거의 하루종일 잠을 자버렸다.. 주말간 화이팅!

##### 느낀점
- 화이팅!

#### 오늘 한 일
- 주말의 2보 전진을 위한 1보 후퇴

#### 내일의 계획
- [ ] Anonymous Feed 관련 FE 작업
- [ ] Question Send Modal 작업? (Friend 관련 작업 풀 받으면)
- [ ] Friendship Model 건드리기

**Comment by koyrkr** [comment]
[2020-11-21-SAT]

작업중인 브랜치:  `feature/backend-friendrequest`

#### 어려웠던 점
- BE를 본격적으로 빡세게 해보았다! 자잘한 시행착오들이 많았는데 구글링 + @ssm0318 의 도움으로 쉽게 해결을 해낼 수 있었다.

##### 느낀점
- BE는 뭔가 고민을 엄청 하면 할수록 그게 나중에 힘을 발휘한다는 느낌이다! 속도가 처음에 안붙어서 걱정을 많이 했지만 하니까 되는 느낌?! 내일 안엔 꼭 Friendship, FriendRequest 관련 작업을 모두 끝내고 싶다! 

#### 오늘 한 일
- Postgresql Attachment!
- Friendship Model + Testing + serializer + API testing (일부)
- FriendRequest Model + Testing + serializer (일부)
- 기타 FE 관련 자잘한 수정들

#### 내일의 계획
- [ ] Question Send Modal 작업? (Friend 관련 작업 풀 받으면)
- [ ] FriendRequest 관련 작업
- [ ] FriendRequest & Friendship 연결 작업!
