### ISSUE TITLE
[Sprint 4] TangerineFrog ssm0318's Daily To-do Coverage Report

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#50]
[전체 to-do](https://github.com/swsnu/swpp2020-team8/issues/46)

_Last Updated:_ 2020/11/16

[Frontend]
- [ ] UserPage
- [ ] Search + Search Results Page (친구 요청, 친구 끊기)

[Backend]
- [x] User search view
~- [ ] JSON validation for Comment, Like, Article, Response, Question, Post, User~
- [x] API testing for Comment
- [x] API testing for Like
- [x] API testing for Response
- [x] API testing for Article
- [x] API testing for Question
- [x] API testing for Post
- [x] API testing for User profile + search
- [x] ML feature
- [x] anonymize authors
- [x] restricted permissions
- [x] friend permissions
- [ ] permissions testing for Article
- [ ] permissions testing for Response
- [ ] permissions testing for Question
- [ ] permissions testing for Post
- [ ] response request & friendship mock update
- [ ] response request ML

**To-do**|**To-do Detail**|**Progress**
:-----:|:-----:|:-----:
misc.|Sonarcloud|0%
| |token bug|100%
| |meeting preparation|50%
| |sprint 4 wrap-up|0%
| | sprint report | 0%
Sprint 3 wrap-up|mock seed|0%
| | is_reply & is_admin_question automation | 100%
[Comment] API Testing|CRUD w/ permissions|100%
[Like] API Testing|CRUD w/ permissions|100%
[Response] API Testing|CRUD w/ permissions|100%
[Question] API Testing|CRUD w/ permissions|100%
| |non CRUD|100%
[Article] API Testing|CRUD w/ permissions|100%
[Post] API Testing|CRUD w/ permissions|100%
| |non CRUD|100%
[User] API Testing|login|100%
| |logout|100%
| |signup|100%
| |JSON validation|100%
[User] search view|implementation|100%
| |testing|100%
ML Feature|implementation|100%
| |testing|100%
| | api | 100%
| | cron | 100%
[FE] User Page|markup|0%
| | API linking| 0%
| | testing | 0%
[FE] Search Page|markup|100%
| | API linking - search| 100%
| | API linking - friend request| 0%
| | testing | 0%
Permissions Implementation|anonymize|100%
| | friend only profile | 100%
| | restricted | 100%
| Permissions Testing | anonymize | 100%
| | restriction | 0%
| | Article | 0%
| | Response | 0%
| | Question | 0%
| | Post | 0%

**Comment by ssm0318** [comment]
[2020-11-15-SUN]

작업중인 브랜치: `feature/backend-serializers`, `test/backend-sprint3`

**오늘의 계획**
-

#### 어려웠던 점
- sonar cloud build가 계속 pass가 되지 않는데 원인을 모르겠다...
- django test plus를 써보려고 하는데 또 새롭다..! DRF testing도 조금 러닝커브가 있는듯
- sprint3에서 API testing이 완료되지 않아서 프론트엔드에서 dependency가 있는 부분들에서 백엔드 에러가 난다.

#### 내일의 계획
- [ ] sonar cloud
- [ ] token bug 해결
- [ ] API testing 예시 사례
- [ ] (가능하면) ML 알아보기 시작

**Comment by ssm0318** [comment]
- [ ] User Page markup - @ssm0318 
- [ ] User Page testing - @ssm0318 
- [ ] User Page api - @ssm0318 
- [X] user Search markup - @ssm0318 
- [ ] user search api - @ssm0318 
- [ ] user search testing - @ssm0318 
- [ ] friend related items api linking & testing - @ssm0318 
- [ ] locust(일) - @ssm0318
